### ISSUE TITLE
Add maps

### ISSUE THREAD

**Issue by DanielBarstow** [windows-on-earth/winearth-webui#21] opened 2024-08-16 14:18 UTC
for each movie, a map of the flight path is essential for the user experience.  Please implement a system to create maps and integrate maps into the movie display page, and the search results page.

Here's one simple way to do this.  In brief, you use a world map as the base (see attached).  then you convert lat / lon values from the image data into X / Y coordinates on the base map.  For example:

If the Earth map shows Earth from 60N to 60S, centered on prime meridian, in a 360 x 120 pixel image, and if the map image has 0,0 in lower left.

Then we grab the lat lon for each image (or maybe every 10th image is enough), and convert with this formula
       X = if W (180 - Deg) else (180 + Deg)
       Y =(if  S (180 - Deg) else (180 + Deg)

![Screenshot 2024-08-16 at 10 09 47 AM](https://github.com/user-attachments/assets/edc14710-2c41-43e2-85d4-7c5e789476ff)

![Screenshot 2024-07-20 at 10 33 15 AM](https://github.com/user-attachments/assets/83aa4588-9106-4f62-b77d-0756ed75fee5)

**Comment by kevincoakley** [comment] 2024-08-16 17:34
Duplicate of https://github.com/windows-on-earth/winearth-webui/issues/19

**Closed by kevincoakley** 2024-08-16 17:34 UTC
